name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:${PATH}" >> $GITHUB_ENV
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"



    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt install -y \
        zip unzip openjdk-17-jdk \
        python3-pip python3-setuptools \
        python3-wheel python3-virtualenv \
        git libncurses-dev libstdc++6 libffi-dev libssl-dev


    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Accept licenses and install build-tools
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bertani-app
        path: bin/*.apk
